
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMzMzNDUz","is_bot":false,"login":"a-k-u-m-a-r","name":"Akshay Kumar"},"headRefName":"AK-RemoveCoursesPage","number":44,"title":"Remove Courses Page","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/44"},{"author":{"id":"MDQ6VXNlcjM4NzAyMjEx","is_bot":false,"login":"tim-choi","name":"Timothy Choi"},"headRefName":"tc-delete","number":43,"title":"FEATURE: Added Delete Button to PersonalSchedules page","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/43"},{"author":{"id":"MDQ6VXNlcjQyOTg1Njg3","is_bot":false,"login":"ericpretzel","name":"Eric W"},"headRefName":"Eric-h2-console-option","number":40,"title":"FEATURE: H2 Console option on NavBar","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/40"},{"author":{"id":"MDQ6VXNlcjQyOTg1Njg3","is_bot":false,"login":"ericpretzel","name":"Eric W"},"headRefName":"Eric-swagger-link","number":39,"title":"FEATURE: Swagger option on NavBar","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/39"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinLavelle-EasierSearch","number":37,"title":"Kevin Lavelle -Easier Search ","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/37"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinLavelle-DefaultQuarter-Modified","number":36,"title":"Kevin Lavelle - Default quarter modified","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinLavelle-LogoButton","number":34,"title":"Kevin Lavelle - logo is now a link","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/34"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinLavelle-CoursesWebTitle","number":33,"title":"Kevin Lavelle - Changed React App to UCSB Courses App","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/33"}]
