
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjM4NzAyMjEx","is_bot":false,"login":"tim-choi","name":"Timothy Choi"},"headRefName":"tc-delete-2","number":54,"title":"FEATURE: Added Delete Button to PersonalSchedules page (pt.2)","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/54"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinLavelle-GradeHistoryJob","number":53,"title":"Kevin Lavelle - Added job for Grade History","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/53"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-issue6","number":49,"title":"Mike - Fixed bug where you can add class to a different quarter's schedule","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/49"},{"author":{"id":"MDQ6VXNlcjYxNjY4MzI3","is_bot":false,"login":"KevinChen0527","name":"Kevin Chen"},"headRefName":"KevinC-FixAddButton","number":48,"title":"KevinC - Fix Add Button","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/48"},{"author":{"id":"MDQ6VXNlcjMzMzMzNDUz","is_bot":false,"login":"a-k-u-m-a-r","name":"Akshay Kumar"},"headRefName":"AK-RemoveCoursesPage","number":44,"title":"Remove Courses Page","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-3/pull/44"}]
